import type { Metadata } from "next";
import './globals.css'
import localFont from "next/font/local";
import TopBar from "./components/TopBar";
import Particles from "./react_bits/Particles";


const myFont = localFont({
  src: [
    {
      path: "./fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-myfont", // creates a CSS variable
});

export const metadata: Metadata = {
  title: "lio",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={` ${myFont.className} min-h-screen bg-black relative`}>
        <header className="h-[54px] w-3xl custom-container sticky top-6 rounded-full bg-white/30 backdrop-blur border">
          <TopBar />
        </header>
        <main>
          {children}
        </main>
        <footer>
          Footer
        </footer>
      </body>
    </html>
  );
}
