import type { Metadata } from "next";
import './globals.css'
import localFont from "next/font/local";
import TopBar from "./components/TopBar";
import Footer from "./components/Footer";


const myFont = localFont({
  src: [
    {
      path: "./fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-myfont", // creates a CSS variable
});

export const metadata: Metadata = {
  title: "lio",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={` ${myFont.className} min-h-screen relative dark:bg-black`}>
        <header className="h-[54px] w-full lg:w-3xl lg:mx-auto sticky top-0 lg:top-6">
          <TopBar />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
